# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "title": "ES90",
  "description": "Датчик у входа"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/2/
Content-Type: application/json

{
  "description": "Перенес датчик на окно"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 39.6,
  "image_model": "D:\\Фото\\IMG_20211231_091424.jpg"
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
