# Generated by Django 4.1.7 on 2023-02-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
