# Generated by Django 4.1.7 on 2023-02-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_sensor_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['id_sensor', 'date'], 'verbose_name': 'Новые замеры', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Новый датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor', verbose_name='Модель датчика'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
