# Generated by Django 4.1.7 on 2023-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['id'], 'verbose_name': 'Новый датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата измерения'),
        ),
    ]
