# Generated by Django 4.1.7 on 2023-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_sensor_options_alter_measurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image_model',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
