# Generated by Django 4.1.7 on 2023-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_alter_measurement_image_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image_model',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
