# Generated by Django 4.1.7 on 2023-02-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_alter_measurement_image_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['sensor', 'date'], 'verbose_name': 'Новые замеры', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='id_sensor',
            new_name='sensor',
        ),
    ]
